# Cops N Robbers 3.0.2 / legacy Unity compatibility
module.id=cnr
module.version=1.0.0
guest.package=com.joydo.minestrikenew
path.rewritePrivate=true

path.alias.0.from=/sdcard/CNRMods
path.alias.0.toFilesRelative=CNRMods
path.alias.1.from=/mnt/sdcard/CNRMods
path.alias.1.toFilesRelative=CNRMods
path.alias.2.from=/storage/emulated/0/CNRMods
path.alias.2.toFilesRelative=CNRMods
path.alias.3.from=/storage/emulated/legacy/CNRMods
path.alias.3.toFilesRelative=CNRMods
path.alias.4.from=/storage/self/primary/CNRMods
path.alias.4.toFilesRelative=CNRMods

property.ro.product.model=CNR64
property.ro.product.device=cnr64

patch.0.name=unity-4.6-legacy-signal-init-bypass
patch.0.address=0x013d29b8
patch.0.expected=0xeb0010f3
patch.0.replacement=0xe1a00000

address.UnityEngine.Input::get_touchCount=0x0142b6c4